# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hayespan的博客
email: 806968607@qq.com
description: > # this means to ignore newlines until "baseurl:"
    一个爱画画的程序猿。
baseurl: "/hayespan-blog" # the subpath of your site, e.g. /blog
url: "https://hayespan.github.io" # the base hostname & protocol for your site
port: 8091
github_username: hayespan

# Build settings
markdown: kramdown
excerpt_separator: ""

# duoshuo 评论
duoshuo_enable: true
duoshuo_username: "hayespangithubio"

# highlighter
highlighter: "pygments"
